services:
  gocast:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    command: -service.debounce=3s
    volumes:
      - ./gocast.json:/etc/gocast/config.json
    ports:
      - 8080:8080
      - 8000:8000

  sources:
    image: jrottenberg/ffmpeg
    command: |
      -hide_banner
      -re -f lavfi -i sine=f=440
      -filter_complex "asplit=4[A][B][C][D]"
      -map [A] -f mp3 http://gocast:8080/streams/foo
      -map [B] -f adts icecast://gocast:8000/bar
      -map [C] -f adts -legacy_icecast 1 icecast://gocast:8000/bar-leg
      -map [D] -f adts srt://gocast:6000?streamid=pub:baz
    depends_on:
      - gocast

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
